const mongoose = require("mongoose");

const userSchema = new mongoose.Schema({
  name: { type: String, required: true },
  email: { type: String, unique: true, required: true },
  password: { type: String, required: true },
  avatar: { type: String },
  phone: { type: String },
  address: {
    street: { type: String },
    city: { type: String },
    state: { type: String },
    postalCode: { type: String },
    country: { type: String },
  },
  role: {
    type: String,
    enum: [
      "accountant",
      "author",
      "admin",
      "alumni_relations",
      "business_analyst",
      "content_creator",
      "course_coordinator",
      "customer_support",
      "data_scientist",
      "dean",
      "department_head",
      "developer",
      "event_coordinator",
      "employee",
      "hr_manager",
      "hod",
      "intern",
      "legal_advisor",
      "maintenance_staff",
      "marketing_manager",
      "operations_manager",
      "product_owner",
      "project_manager",
      "principal",
      "qa_lead",
      "recruiter",
      "registrar",
      "researcher",
      "sales_executive",
      "student",
      "instructor",
      "superadmin",
      "support_engineer",
      "student",
      "tech_lead",
      "test_engineer",
      "user",
      "ux_ui_designer",
      "vendor",
      "outlet",
      "delivery_person",
    ],
    default: "user",
  },
  otp: { type: String },
  otpExpires: { type: Date },
  createdAt: { type: Date, default: Date.now },
  updatedAt: { type: Date, default: Date.now },
});

const User = mongoose.model("User", userSchema);

module.exports = User;
